import { type NextPage } from "next";
import Head from "next/head";
import { CourseCard } from "~/components/CourseCard";
import { Flex, createStyles } from "@mantine/core";

const useStyles = createStyles(() => ({
  wrapper: {
    padding: 25,
    width: "100%",
    height: "100%",
    overflow: "hidden"
  },
}));

const coursesList = [
  {
    title: "React beginner course",
    author: "admin",
    topic: "react",
    imagesrc: "/react.jpg",
    raiting: 5,
    raiting_pepole: 32123,
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Angular advanced course",
    author: "admin",
    topic: "angular",
    imagesrc: "/angular.jpg",
    raiting: 1,
    raiting_pepole: 25,
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Vue intermediate course",
    author: "admin",
    topic: "vue",
    imagesrc: "/vue.jpg",
    raiting: 4.5,
    raiting_pepole: 900,
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Svelte basics course",
    author: "admin",
    topic: "svelte",
    imagesrc: "/svelte.jpg",
    raiting: 4.2,
    raiting_pepole: 1300,
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Node.js fundamentals course",
    author: "admin",
    topic: "node.js",
    imagesrc: "/nodejs.jpg",
    raiting: 3.8,
    raiting_pepole: 1200,
    badges: ["javascript"],
  },
  {
    title: "Express.js advanced course",
    author: "admin",
    topic: "express.js",
    imagesrc: "/expressjs.jpg",
    raiting: 2.5,
    raiting_pepole: 150,
    badges: ["javascript"],
  },
];

const Courses: NextPage = () => {
  const { classes } = useStyles();

  return (
    <>
      <Head>
        <title>Course Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.wrapper}>
        <Flex
          direction="row"
          justify="flex-start"
          align="flex-start"
          gap="lg"
          wrap="wrap"
        >
          {coursesList.map((course) => (
              <CourseCard key={course.title} {...course} />
          ))}
        </Flex>
      </main>
    </>
  );
}

export default Courses;
