import { type NextPage } from "next";
import Head from "next/head";
import { CourseCard } from "~/components/CourseCard";
import { Flex, Grid, createStyles } from "@mantine/core";

const useStyles = createStyles((theme) => ({
  wrapper: {
    padding: 25,
  },
}));

const coursesList = [
  {
    title: "React beginner course",
    author: "admin",
    topic: "react",
    imagesrc: "/react.jpg",
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Angular advanced course",
    author: "admin",
    topic: "angular",
    imagesrc: "/angular.jpg",
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Vue intermediate course",
    author: "admin",
    topic: "vue",
    imagesrc: "/vue.jpg",
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Svelte basics course",
    author: "admin",
    topic: "svelte",
    imagesrc: "/svelte.jpg",
    badges: ["javascript", "html", "css"],
  },
  {
    title: "Node.js fundamentals course",
    author: "admin",
    topic: "node.js",
    imagesrc: "/nodejs.jpg",
    badges: ["javascript"],
  },
  {
    title: "Express.js advanced course",
    author: "admin",
    topic: "express.js",
    imagesrc: "/expressjs.jpg",
    badges: ["javascript"],
  },
];
function courses() {
  const { classes } = useStyles();

  return (
    <>
      <Head>
        <title>Course Platform</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classes.wrapper}>
        <Flex
          direction="row"
          justify="flex-start"
          align="flex-start"
          gap="lg"
          wrap="wrap"
        >
          {coursesList.map((course) => (
              <CourseCard key={course.title} {...course} />
          ))}
        </Flex>
        {/* <Grid
          gutter={"xl"}
          align="flex-start"
          justify="space-between"
          sx={{ width: "100%", height: "100%" }}
        >
          {coursesList.map((course) => (
            <Grid.Col span={4} key={course.title}>
              <CourseCard {...course} />
            </Grid.Col>
          ))}
        </Grid> */}
      </main>
    </>
  );
}

export default courses;
